name: deloy-tickets

on:
  push:
    branches: 
      - master
    paths:
      - 'tickets/**'

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && docker build -t ngquangan/ticketing-tickets .
      # login to docker hub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ngquangan/ticketing-tickets
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # Restart deployment to get latest code from image
      - run: kubectl rollout restart deployment tickets-depl