name: deloy-client

on:
  push:
    branches: 
      - master
    paths:
      - 'client/**'

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t ngquangan/ticketing-client .
      # login to docker hub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ngquangan/ticketing-client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # Restart deployment to get latest code from image
      - run: kubectl rollout restart deployment client-depl